version: '3.1'

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
    restart: always

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: sdfj234
    restart: always

  wordpress:
    image: wordpress:4.9.1-php7.1-fpm
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_NAME: nmdb
      WORDPRESS_TABLE_PREFIX: nm_
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: sdfj234
    restart: always
